"""initial schema

Revision ID: 784aacaef1cd
Revises: 
Create Date: 2026-07-17 18:02:52.696993

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '784aacaef1cd'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('concept_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('graph_node',
    sa.Column('node_type', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name='ck_valid_from_valid_to_interval'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('legal_document',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_hash', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('legal_rule',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('legal_subject',
    sa.Column('subject_type', sa.Enum('COMPANY', 'LISTED_COMPANY', 'PERSON', 'REGULATOR', name='subject_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('unified_credit_code', sa.String(length=50), nullable=True),
    sa.Column('listed', sa.Boolean(), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('code', sa.Enum('READER', 'COMPLIANCE_USER', 'KNOWLEDGE_EDITOR', 'LEGAL_REVIEWER', 'TECHNICAL_REVIEWER', 'PUBLISHER', 'AUDITOR', 'SYSTEM_ADMIN', name='rbac_role_code'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('role_type',
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenant',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('article',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('article_no', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['legal_document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'article_no', name='uq_article_document_no')
    )
    op.create_table('audit_event',
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('resource_type', sa.String(length=80), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('resource_version', sa.String(length=100), nullable=True),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('reason_code', sa.String(length=80), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_event_tenant_time', 'audit_event', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index('idx_audit_event_trace', 'audit_event', ['trace_id'], unique=False)
    op.create_table('compliance_check',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('evaluation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ruleset_id', sa.String(length=100), nullable=False),
    sa.Column('ruleset_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='compliance_check_status'), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['legal_subject.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_compliance_check_idem')
    )
    op.create_table('concept_version',
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=False),
    sa.Column('review_status', sa.String(length=30), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name='ck_valid_from_valid_to_interval'),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor_subject_id', sa.UUID(), nullable=True),
    sa.Column('object_type', sa.String(length=80), nullable=True),
    sa.Column('object_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['actor_subject_id'], ['legal_subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_file', sa.Text(), nullable=True),
    sa.Column('page_no', sa.Integer(), nullable=True),
    sa.Column('quote_text', sa.Text(), nullable=True),
    sa.Column('source_hash', sa.String(length=128), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('fact_type', sa.String(length=80), nullable=False),
    sa.Column('subject_ref', sa.UUID(), nullable=True),
    sa.Column('predicate', sa.String(length=80), nullable=False),
    sa.Column('object_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name='ck_valid_from_valid_to_interval'),
    sa.ForeignKeyConstraint(['company_id'], ['legal_subject.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fact_tenant_company', 'fact', ['tenant_id', 'company_id'], unique=False)
    op.create_table('graph_edge',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=80), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('valid_from', sa.Date(), nullable=True),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name='ck_valid_from_valid_to_interval'),
    sa.ForeignKeyConstraint(['source_id'], ['graph_node.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['graph_node.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_graph_edge_relation', 'graph_edge', ['relation_type'], unique=False)
    op.create_index('idx_graph_edge_source', 'graph_edge', ['source_id'], unique=False)
    op.create_index('idx_graph_edge_target', 'graph_edge', ['target_id'], unique=False)
    op.create_table('idempotency_record',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=128), nullable=False),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_idempotency_key_tenant', 'idempotency_record', ['tenant_id', 'idempotency_key'], unique=True)
    op.create_table('legal_rule_version',
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'CHANGES_REQUESTED', 'LEGAL_APPROVED', 'TECH_APPROVED', 'PUBLISHED', 'DEPRECATED', 'UNVERIFIED', name='rule_review_status'), nullable=False),
    sa.Column('subject_type', sa.String(length=100), nullable=True),
    sa.Column('modality', sa.String(length=30), nullable=False),
    sa.Column('condition_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('requirement_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('exception_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consequence_expression', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('submitted_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name='ck_effective_from_effective_to_interval'),
    sa.ForeignKeyConstraint(['rule_id'], ['legal_rule.id'], ),
    sa.ForeignKeyConstraint(['submitted_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'version_no', name='uq_rule_version_no')
    )
    op.create_table('legal_version',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_name', sa.String(length=255), nullable=False),
    sa.Column('promulgated_at', sa.Date(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('version_hash', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name='ck_effective_from_effective_to_interval'),
    sa.ForeignKeyConstraint(['document_id'], ['legal_document.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('organization_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['legal_subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', 'tenant_id', name='uq_user_role_scope')
    )
    op.create_table('article_version',
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('legal_version_id', sa.UUID(), nullable=False),
    sa.Column('chapter_no', sa.String(length=50), nullable=True),
    sa.Column('section_no', sa.String(length=50), nullable=True),
    sa.Column('article_text', sa.Text(), nullable=False),
    sa.Column('normalized_text', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name='ck_valid_from_valid_to_interval'),
    sa.ForeignKeyConstraint(['article_id'], ['article.id'], ),
    sa.ForeignKeyConstraint(['legal_version_id'], ['legal_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'legal_version_id', name='uq_article_version_unique')
    )
    op.create_table('conclusion',
    sa.Column('compliance_check_id', sa.UUID(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('result_status', sa.Enum('TRUE', 'FALSE', 'UNKNOWN', 'CONFLICT', 'NOT_APPLICABLE', name='truth_value'), nullable=False),
    sa.Column('missing_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applicable_reason', sa.Text(), nullable=True),
    sa.Column('excluded_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compliance_check_id'], ['compliance_check.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['legal_rule_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fact_evidence',
    sa.Column('fact_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=False),
    sa.Column('support_type', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['fact_id'], ['fact.id'], ),
    sa.PrimaryKeyConstraint('fact_id', 'evidence_id')
    )
    op.create_table('review_decision',
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_user_id', sa.UUID(), nullable=False),
    sa.Column('review_type', sa.Enum('LEGAL', 'TECHNICAL', name='review_type'), nullable=False),
    sa.Column('decision', sa.Enum('APPROVED', 'CHANGES_REQUESTED', name='review_decision_type'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['legal_rule_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_assignment',
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role_type_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=True),
    sa.Column('valid_from', sa.Date(), nullable=False),
    sa.Column('valid_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('valid_to IS NULL OR valid_to > valid_from', name='ck_valid_from_valid_to_interval'),
    sa.ForeignKeyConstraint(['company_id'], ['legal_subject.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['legal_subject.id'], ),
    sa.ForeignKeyConstraint(['role_type_id'], ['role_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_test_case',
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('case_type', sa.Enum('PASS', 'VIOLATION', 'BOUNDARY', 'MISSING_FACT', 'NOT_APPLICABLE', 'EXCEPTION', 'CONFLICT', name='rule_test_case_type'), nullable=False),
    sa.Column('input_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expected_status', sa.String(length=30), nullable=False),
    sa.Column('not_applicable_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_version_id'], ['legal_rule_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proof',
    sa.Column('conclusion_id', sa.UUID(), nullable=False),
    sa.Column('root_step_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conclusion_id'], ['conclusion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('conclusion_id')
    )
    op.create_table('rule_source',
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('article_version_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_version_id'], ['article_version.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['legal_rule_version.id'], ),
    sa.PrimaryKeyConstraint('rule_version_id', 'article_version_id')
    )
    op.create_table('proof_step',
    sa.Column('proof_id', sa.UUID(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=True),
    sa.Column('input_facts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_state', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['proof_id'], ['proof.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['legal_rule_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proof_id', 'sequence_no', name='uq_proof_step_sequence')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proof_step')
    op.drop_table('rule_source')
    op.drop_table('proof')
    op.drop_table('rule_test_case')
    op.drop_table('role_assignment')
    op.drop_table('review_decision')
    op.drop_table('fact_evidence')
    op.drop_table('conclusion')
    op.drop_table('article_version')
    op.drop_table('user_role')
    op.drop_table('organization')
    op.drop_table('legal_version')
    op.drop_table('legal_rule_version')
    op.drop_index('idx_idempotency_key_tenant', table_name='idempotency_record')
    op.drop_table('idempotency_record')
    op.drop_index('idx_graph_edge_target', table_name='graph_edge')
    op.drop_index('idx_graph_edge_source', table_name='graph_edge')
    op.drop_index('idx_graph_edge_relation', table_name='graph_edge')
    op.drop_table('graph_edge')
    op.drop_index('idx_fact_tenant_company', table_name='fact')
    op.drop_table('fact')
    op.drop_table('evidence')
    op.drop_table('event')
    op.drop_table('concept_version')
    op.drop_table('compliance_check')
    op.drop_index('idx_audit_event_trace', table_name='audit_event')
    op.drop_index('idx_audit_event_tenant_time', table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_table('article')
    op.drop_table('user')
    op.drop_table('tenant')
    op.drop_table('role_type')
    op.drop_table('role')
    op.drop_table('legal_subject')
    op.drop_table('legal_rule')
    op.drop_table('legal_document')
    op.drop_table('graph_node')
    op.drop_table('concept')
    # ### end Alembic commands ###
