"""add rule_set and rule_set_member; compliance_check.rule_set_id

Revision ID: e97de187ca96
Revises: 784aacaef1cd
Create Date: 2026-07-17 20:00:59.322605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e97de187ca96'
down_revision: Union[str, Sequence[str], None] = '784aacaef1cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rule_set',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'DEPRECATED', name='rule_set_status'), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_to IS NULL OR effective_to > effective_from', name='ck_effective_from_effective_to_interval'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version_no', name='uq_rule_set_code_version')
    )
    op.create_table('rule_set_member',
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_set.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['legal_rule_version.id'], ),
    sa.PrimaryKeyConstraint('rule_set_id', 'rule_version_id')
    )
    op.add_column('compliance_check', sa.Column('rule_set_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'compliance_check', 'rule_set', ['rule_set_id'], ['id'])
    op.drop_column('compliance_check', 'ruleset_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('compliance_check', sa.Column('ruleset_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'compliance_check', type_='foreignkey')
    op.drop_column('compliance_check', 'rule_set_id')
    op.drop_table('rule_set_member')
    op.drop_table('rule_set')
    # ### end Alembic commands ###
